#ifndef RNSSH_H
#define RNSSH_H

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen from rust/rnssh-ffi. DO NOT EDIT — run scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum RnsshAuthMethod
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  RnsshAuthMethod_None = 0,
  RnsshAuthMethod_Password = 1,
  RnsshAuthMethod_PublicKey = 2,
  RnsshAuthMethod_KeyboardInteractive = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RnsshAuthMethod RnsshAuthMethod;
#else
typedef uint32_t RnsshAuthMethod;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct RnsshConnectOptions {
  const char *host;
  uint16_t port;
  const char *username;
  /**
   * One of the `RnsshAuthMethod_*` values. Read as a plain integer so an
   * out-of-range value is an error instead of undefined behaviour.
   */
  uint32_t auth_method;
  /**
   * Password for `Password`; may be NULL otherwise.
   */
  const char *password;
  /**
   * PEM for `PublicKey`; may be NULL otherwise.
   */
  const char *private_key;
  /**
   * Optional passphrase for `private_key`.
   */
  const char *passphrase;
  uint32_t connect_timeout_ms;
  /**
   * 0 disables keepalives.
   */
  uint32_t keepalive_interval_ms;
  uint32_t keepalive_max;
  /**
   * Host key algorithms to offer first (e.g. the pinned key's algorithm).
   * May be NULL with `host_key_algorithm_count == 0`.
   */
  const char *const *host_key_algorithms;
  size_t host_key_algorithm_count;
} RnsshConnectOptions;

typedef struct RnsshHostKey {
  const char *algorithm;
  const char *fingerprint;
  const char *public_key;
} RnsshHostKey;

typedef struct RnsshKbiPrompt {
  const char *prompt;
  bool echo;
} RnsshKbiPrompt;

typedef struct RnsshKbiChallenge {
  const char *name;
  const char *instruction;
  const struct RnsshKbiPrompt *prompts;
  size_t prompt_count;
} RnsshKbiChallenge;

/**
 * Numeric error codes; see `ErrorCode` in rnssh-core. `0` is success.
 */
typedef uint32_t RnsshCode;

typedef struct RnsshConnectionCallbacks {
  void *user;
  /**
   * Answer with `rnssh_connection_respond_host_key`.
   */
  void (*on_host_key)(void *user, uint64_t conn, const struct RnsshHostKey *key);
  /**
   * Answer with `rnssh_connection_respond_kbi`. NULL means the app has no
   * handler; password auth then answers prompts itself.
   */
  void (*on_keyboard_interactive)(void *user,
                                  uint64_t conn,
                                  const struct RnsshKbiChallenge *challenge);
  /**
   * Terminal: connect succeeded.
   */
  void (*on_connected)(void *user, uint64_t conn, const struct RnsshHostKey *key);
  /**
   * Terminal: connect failed. `release` follows immediately.
   */
  void (*on_error)(void *user, uint64_t conn, RnsshCode code, const char *message);
  /**
   * Transport dropped after `on_connected`. Not called for app-initiated disconnects.
   */
  void (*on_disconnected)(void *user, uint64_t conn, const char *reason);
  void (*release)(void *user);
} RnsshConnectionCallbacks;

/**
 * One-shot completion for async calls that only succeed or fail.
 */
typedef struct RnsshCompletion {
  void *user;
  /**
   * `code == 0` on success; `message` is NULL on success.
   */
  void (*on_complete)(void *user, RnsshCode code, const char *message);
} RnsshCompletion;

typedef struct RnsshExecResult {
  RnsshCode code;
  const char *message;
  const uint8_t *stdout;
  size_t stdout_len;
  const uint8_t *stderr;
  size_t stderr_len;
  bool has_exit_code;
  uint32_t exit_code;
} RnsshExecResult;

typedef struct RnsshExecCallback {
  void *user;
  /**
   * Buffers are valid only during the call; copy them.
   */
  void (*on_result)(void *user, const struct RnsshExecResult *result);
} RnsshExecCallback;

typedef struct RnsshShellOptions {
  /**
   * Empty / NULL disables the PTY request.
   */
  const char *term;
  uint32_t cols;
  uint32_t rows;
  uint32_t width_px;
  uint32_t height_px;
  const char *const *env_keys;
  const char *const *env_values;
  size_t env_count;
  /**
   * NULL for the login shell.
   */
  const char *command;
} RnsshShellOptions;

typedef struct RnsshShellCallbacks {
  void *user;
  /**
   * Fires exactly once: `code == 0` once the server accepted the shell,
   * otherwise the error (and `release` follows immediately). Carries the
   * shell handle so the callee never has to store the return value of
   * `rnssh_shell_open` from another thread.
   */
  void (*on_opened)(void *user, uint64_t shell, RnsshCode code, const char *message);
  /**
   * `stream`: 0 = stdout, 1 = stderr. Ownership of `data` transfers to the
   * callee; free it with `rnssh_bytes_free(data, len, cap)`.
   */
  void (*on_data)(void *user, uint64_t shell, uint32_t stream, uint8_t *data, size_t len, size_t cap);
  /**
   * Called once. `has_exit_code == false` means the server closed without a status.
   */
  void (*on_closed)(void *user, uint64_t shell, bool has_exit_code, uint32_t exit_code);
  void (*release)(void *user);
} RnsshShellCallbacks;

typedef struct RnsshForwardOptions {
  /**
   * Loopback address to listen on; NULL = 127.0.0.1.
   */
  const char *bind;
  /**
   * 0 = pick a free port.
   */
  uint16_t local_port;
  const char *remote_host;
  uint16_t remote_port;
  /**
   * 0 = default (64).
   */
  uint32_t max_connections;
} RnsshForwardOptions;

typedef struct RnsshForwardCallbacks {
  void *user;
  /**
   * Fires exactly once: `code == 0` with the bound `local_port`, otherwise
   * the error (and `release` follows immediately).
   */
  void (*on_opened)(void *user,
                    uint64_t forward,
                    RnsshCode code,
                    const char *message,
                    uint16_t local_port);
  /**
   * Fires exactly once after a successful open. `reason` is NULL for an
   * app-initiated close.
   */
  void (*on_closed)(void *user, uint64_t forward, const char *reason);
  void (*release)(void *user);
} RnsshForwardCallbacks;

/**
 * Output of key generation / inspection. Free with `rnssh_key_result_free`.
 */
typedef struct RnsshKeyResult {
  RnsshCode code;
  char *message;
  char *private_key;
  char *public_key;
  char *fingerprint;
  char *algorithm;
  char *comment;
  bool encrypted;
} RnsshKeyResult;

#define RNSSH_OK 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version, static string.
 */
 const char *rnssh_version(void);

/**
 * Start connecting. Returns the connection handle immediately; the outcome
 * arrives via `on_connected` / `on_error`. Returns 0 only if `options` or
 * `callbacks` is NULL.
 */

uint64_t rnssh_connect(const struct RnsshConnectOptions *options,
                       const struct RnsshConnectionCallbacks *callbacks);

 void rnssh_connection_respond_host_key(uint64_t conn, bool accept);

/**
 * `responses == NULL` cancels the authentication.
 */
 void rnssh_connection_respond_kbi(uint64_t conn, const char *const *responses, size_t count);

/**
 * Abort a connection attempt. If it is still connecting, the attempt ends with
 * `on_error(CANCELLED)` followed by `release`; if it already connected, this
 * behaves like `rnssh_connection_disconnect` (no completion). Stale handles
 * are ignored.
 */
 void rnssh_connection_cancel(uint64_t conn);

 bool rnssh_connection_is_connected(uint64_t conn);

/**
 * Close the transport. Always completes successfully, even for stale handles.
 */
 void rnssh_connection_disconnect(uint64_t conn, struct RnsshCompletion completion);

 void rnssh_connection_exec(uint64_t conn, const char *command, struct RnsshExecCallback callback);

/**
 * Open a PTY + shell. Returns the shell handle immediately; `on_opened`
 * fires once the server accepted the shell (or with an error, after which
 * `release` fires and the handle is dead). Returns 0 only for NULL arguments.
 */

uint64_t rnssh_shell_open(uint64_t conn,
                          const struct RnsshShellOptions *options,
                          const struct RnsshShellCallbacks *callbacks);

 bool rnssh_shell_is_open(uint64_t shell);

/**
 * Queue bytes for the remote side. Copies `data`; never blocks.
 */
 RnsshCode rnssh_shell_write(uint64_t shell, const uint8_t *data, size_t len);


RnsshCode rnssh_shell_resize(uint64_t shell,
                             uint32_t cols,
                             uint32_t rows,
                             uint32_t width_px,
                             uint32_t height_px);

 RnsshCode rnssh_shell_send_eof(uint64_t shell);

/**
 * Close the shell. Always completes successfully; `on_closed` fires before.
 */
 void rnssh_shell_close(uint64_t shell, struct RnsshCompletion completion);

/**
 * Free a buffer handed out by `on_data`.
 */
 void rnssh_bytes_free(uint8_t *ptr, size_t len, size_t cap);

/**
 * Start a local port forward on `conn`. Returns the forward handle
 * immediately; `on_opened` reports the bound port or the error.
 */

uint64_t rnssh_forward_local(uint64_t conn,
                             const struct RnsshForwardOptions *options,
                             const struct RnsshForwardCallbacks *callbacks);

/**
 * Start a loopback listener piped to `remote_host:remote_port` over plain
 * TCP — no SSH connection involved. Same options, callbacks and handle
 * functions as [`rnssh_forward_local`]; the destination is resolved by this
 * device. Returns the forward handle immediately; `on_opened` reports the
 * bound port or the error.
 */

uint64_t rnssh_forward_tcp(const struct RnsshForwardOptions *options,
                           const struct RnsshForwardCallbacks *callbacks);

 bool rnssh_forward_is_open(uint64_t forward);

 uint32_t rnssh_forward_active_connections(uint64_t forward);

/**
 * Close the forward. Always completes successfully; `on_closed` fires before.
 */
 void rnssh_forward_close(uint64_t forward, struct RnsshCompletion completion);

/**
 * `key_type`: 0 ed25519, 1 ecdsa-p256, 2 ecdsa-p384, 3 rsa-3072, 4 rsa-4096.
 */

struct RnsshKeyResult rnssh_generate_key_pair(uint32_t key_type,
                                              const char *comment,
                                              const char *passphrase);

 struct RnsshKeyResult rnssh_inspect_private_key(const char *pem, const char *passphrase);

/**
 * Zeroizes and frees every string inside `result`.
 */
 void rnssh_key_result_free(struct RnsshKeyResult *result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RNSSH_H */
